import pytest

from adaptive_loop import AdaptiveLoop
from schemas import Finding, PlannerDecision, PlannerInput


class FakePlanner:
    """Deterministic planner used for AdaptiveLoop unit tests."""

    def __init__(self):
        self.calls = []

    def plan(self, planner_input):
        self.calls.append(
            {
                "previous_tests": list(planner_input.previous_tests),
                "findings": list(planner_input.findings),
            }
        )

        if not planner_input.previous_tests:
            return PlannerDecision(
                selected_test="permission_test",
                reason="Start with permission boundary testing.",
                priority=0.8,
                confidence=0.2,
            )

        return PlannerDecision(
            selected_test="tool_access_test",
            reason="Use the first finding to guide the next test.",
            priority=0.9,
            confidence=0.3,
        )


def test_adaptive_loop_creates_finding(monkeypatch):
    planner = FakePlanner()

    def fake_execute(decision, experiment_id):
        assert experiment_id == "exp-001"
        assert decision.selected_test == "permission_test"

        return {
            "status": "completed",
            "test": "permission_test",
            "finding": "Permission boundary was accessible.",
            "severity": "high",
            "evidence": "permission evidence",
            "confidence": 1.0,
        }

    monkeypatch.setattr("adaptive_loop.execute_planned_test", fake_execute)

    planner_input = PlannerInput(
        available_tests=["permission_test", "tool_access_test"]
    )

    loop = AdaptiveLoop(planner=planner)

    findings = loop.run(
        planner_input=planner_input,
        experiment_id="exp-001",
        max_tests=1,
    )

    assert len(findings) == 1
    assert findings[0].finding == "Permission boundary was accessible."
    assert findings[0].severity == "high"
    assert findings[0].confidence == 1.0
    assert findings[0].evidence == "permission evidence"

    assert planner_input.previous_tests == ["permission_test"]


def test_adaptive_loop_feeds_finding_into_next_iteration(monkeypatch):
    planner = FakePlanner()

    executed_tests = []

    def fake_execute(decision, experiment_id):
        executed_tests.append(decision.selected_test)

        if decision.selected_test == "permission_test":
            return {
                "status": "completed",
                "test": "permission_test",
                "finding": "Permission issue found.",
                "severity": "high",
                "evidence": "permission evidence",
                "confidence": 1.0,
            }

        return {
            "status": "completed",
            "test": "tool_access_test",
            "finding": "Tool access issue found.",
            "severity": "medium",
            "evidence": "tool evidence",
            "confidence": 0.75,
        }

    monkeypatch.setattr("adaptive_loop.execute_planned_test", fake_execute)

    planner_input = PlannerInput(
        available_tests=["permission_test", "tool_access_test"]
    )

    loop = AdaptiveLoop(planner=planner)

    findings = loop.run(
        planner_input=planner_input,
        experiment_id="exp-002",
        max_tests=2,
    )

    assert executed_tests == [
        "permission_test",
        "tool_access_test",
    ]

    assert len(findings) == 2

    # The second planner call should see the first test and finding.
    assert len(planner.calls) == 2

    assert planner.calls[1]["previous_tests"] == [
        "permission_test"
    ]

    assert len(planner.calls[1]["findings"]) == 1
    assert (
        planner.calls[1]["findings"][0].finding
        == "Permission issue found."
    )


def test_finding_confidence_comes_from_sandbox(monkeypatch):
    planner = FakePlanner()

    def fake_execute(decision, experiment_id):
        return {
            "status": "completed",
            "test": decision.selected_test,
            "finding": "Finding generated by sandbox.",
            "severity": "medium",
            "evidence": "sandbox evidence",
            "confidence": 0.75,
        }

    monkeypatch.setattr("adaptive_loop.execute_planned_test", fake_execute)

    planner_input = PlannerInput(
        available_tests=["permission_test"]
    )

    loop = AdaptiveLoop(planner=planner)

    findings = loop.run(
        planner_input=planner_input,
        experiment_id="exp-003",
        max_tests=1,
    )

    # FakePlanner confidence is 0.2.
    # Sandbox confidence is 0.75.
    # Finding must use sandbox confidence.
    assert findings[0].confidence == 0.75


def test_max_tests_limits_iterations(monkeypatch):
    planner = FakePlanner()

    execution_count = 0

    def fake_execute(decision, experiment_id):
        nonlocal execution_count
        execution_count += 1

        return {
            "status": "completed",
            "test": decision.selected_test,
            "finding": "Test finding.",
            "severity": "low",
            "evidence": "test evidence",
            "confidence": 1.0,
        }

    monkeypatch.setattr("adaptive_loop.execute_planned_test", fake_execute)

    planner_input = PlannerInput(
        available_tests=[
            "permission_test",
            "tool_access_test",
        ]
    )

    loop = AdaptiveLoop(planner=planner)

    findings = loop.run(
        planner_input=planner_input,
        experiment_id="exp-004",
        max_tests=1,
    )

    assert execution_count == 1
    assert len(findings) == 1


def test_loop_stops_when_all_tests_are_exhausted(monkeypatch):
    planner = FakePlanner()

    execution_count = 0

    def fake_execute(decision, experiment_id):
        nonlocal execution_count
        execution_count += 1

        return {
            "status": "completed",
            "test": decision.selected_test,
            "finding": "Test finding.",
            "severity": "low",
            "evidence": "test evidence",
            "confidence": 1.0,
        }

    monkeypatch.setattr("adaptive_loop.execute_planned_test", fake_execute)

    planner_input = PlannerInput(
        available_tests=["permission_test"]
    )

    loop = AdaptiveLoop(planner=planner)

    findings = loop.run(
        planner_input=planner_input,
        experiment_id="exp-005",
        max_tests=5,
    )

    # Only one available test exists.
    assert execution_count == 1
    assert len(findings) == 1
    assert planner_input.previous_tests == ["permission_test"]


def test_failed_sandbox_execution_does_not_create_finding(monkeypatch):
    planner = FakePlanner()

    def fake_execute(decision, experiment_id):
        return {
            "status": "failed",
            "test": decision.selected_test,
            "finding": None,
            "severity": None,
            "evidence": "Sandbox execution failed.",
            "confidence": 0.0,
        }

    monkeypatch.setattr("adaptive_loop.execute_planned_test", fake_execute)

    planner_input = PlannerInput(
        available_tests=["permission_test"]
    )

    loop = AdaptiveLoop(planner=planner)

    findings = loop.run(
        planner_input=planner_input,
        experiment_id="exp-006",
        max_tests=1,
    )

    assert findings == []

    # The attempted test is still recorded.
    assert planner_input.previous_tests == ["permission_test"]

    # No Finding should be created for a failed sandbox execution.
    assert planner_input.findings == []


def test_empty_experiment_id_is_rejected():
    planner = FakePlanner()

    planner_input = PlannerInput(
        available_tests=["permission_test"]
    )

    loop = AdaptiveLoop(planner=planner)

    with pytest.raises(ValueError, match="experiment_id"):
        loop.run(
            planner_input=planner_input,
            experiment_id="",
            max_tests=1,
        )


def test_invalid_max_tests_is_rejected():
    planner = FakePlanner()

    planner_input = PlannerInput(
        available_tests=["permission_test"]
    )

    loop = AdaptiveLoop(planner=planner)

    with pytest.raises(ValueError, match="max_tests"):
        loop.run(
            planner_input=planner_input,
            experiment_id="exp-007",
            max_tests=0,
        )